# Generated by Django 5.2.5 on 2025-08-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_alter_customuser_role'),
    ]

    operations = [
    ]
