# Generated by Django 5.2.5 on 2025-08-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250820_2326'),
    ]

    operations = [
    ]
